# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacy - Jekyll/Macy
email: studio@harrycresswell.com
description: > # this means to ignore newlines until "baseurl:"
  Jacy combines Macy.js the lightweight, dependency-free, masonry layout with the power of Jekyll, the static site generator.
baseurl: "/jacy" # the subpath of your site, e.g. /blog
url: "http://harrycresswell.github.io/" # the base hostname & protocol for your site
twitter_username: twitter
github_username:  github

# Build settings
markdown: kramdown

# Remove hashtag below and update username to enable Disqus comments
# disqus_shortname: usernamehere

# files and folders to exlude from the Jekyll build
exclude: ["node_modules", "gulpfile.js", "package.json"]
